   
	var quotes = [
		["I'm not chewing it I'm just sucking it in my mouth. -KilobyteKeith Dead by Daylight 02/20/2020"], 
		["Just because you mate doesn't mean you are happy. -KilobyteKeith Planet Zoo 03/15/2020"], 
		["Take it all over the chest. -KilobyteKeith Control 05/27/2020"], 
		["I'm going in deep! - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["OoOoH she's got a little pussy zipper! - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["I would like 1 wet dream please. - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["How do I get my dick hard? - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["Can I take my pants off? - kilobytekeith Cyberpunk 2077 12/11/2020"], 
		["Lets put this dick to use, dick tease. - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["I'll bring extra panties to cream in. - BinaryDigit Cyberpunk 2077 12/11/2020"], 
		["I like when things get sticky. -KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["I just want to see my dude's dick again! -KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["I like a deep slot. - KilobyteKeith Amnesia: Rebirth 12/28/2020"], 
		["When in doubt, crank it out! - KilobyteKeith Amnesia: Rebirth 12/28/2020"], 
		["Where is the hole? I can't find it! - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["Come on Dani, someone’s gotta show these hoes how to do it. - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["Make my pussy throb! - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["I'll put anything in my mouth. - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["I’ll ride the Keke Express. - BinaryDigit Call of Duty: Warzone 12/31/2020"], 
		["Can I draw a penis on it? - KilobyteKeith Call of Duty: Warzone 12/31/2020"], 
		["I can't swallow! -KiloybyteKeith Call of Duty: Warzone 12/31/2020"], 
		["I feel like I'm close. - KilobyteKeith Song of Horror 01/03/2021"], 
		["Followinl the ol’ jizz trail - KilobyteKeith Song of Horror 01/05/2021"], 
		["Oh God!! It’s covered in jizz! It looks like my closet. - KilobyteKeith Song of Horror 01/05/2021"], 
		["I hope every guy watching this is fully erect by the sound of my voice. - KilobyteKeith Song of Horror 01/05/2021"], 
		["....just like stroking a dick. - BinaryDigit Song of Horror 01/05/2021"], 
		["That right there is a vagina opener. - KilobyteKeith Song of Horror 01/12/2021"], 
		["two in the pink one in the stink - KilobyteKeith Song of Horror 01/12/2021"], 
		["How do I start blowing? -- KilobyteBot Song of Horror 01/12/2021"], 
		["you better bring some bitches Tyler cuz we’re gonna fuck em RAW - KilobyteKeith Song of Horror 01/12/2021"], 
		["You remind me of my pinkie toe...little, cute and I'll probably bang you on the coffee table later tonight. - Tylersoyer Song of Horror 01/12/2021"], 
		["Get your bitch ass pussy out my face - KilobyteKeith Song of Horror 01/12/2021"], 
		["Britt would be wild and probably put five fingers in ya Binary. Use you like a sock puppet -- KilobyteKeith Song of Horror 01/12/2021"], 
		["nothing wrong with walking in a room and getting fucked - Tylersoyer Song of Horror 01/12/2021"], 
		["AHHH FUCK ME IN THE ASS!! - KilobyteKeith Song of Horror 01/13/2021"], 
		["My hands are NOT on my cock! - KilobyteKeith The House of the Dead: Overkill 01/14/2021"], 
		["portable hand jobs now - Tylersoyer The House of the Dead: Overkill 01/14/2021"], 
		["No I will stay wet - BinaryDigit Call of Duty: Black Ops Cold War 01/17/2021"], 
		["She's also aware of my big black cock fetish - KilobyteKeith Call of Duty: Black Ops Cold War 01/17/2021"], 
		["Hey at least when we order a Keke version of a penis we end up getting a loose vagina instead #WishFails - RoyalBrrittneyyygns Stardew Valley 01/24/2021"], 
		["even if you have A cups, I don’t care, I’ll still suck them - KilobyteKeith Stardew Valley 01/24/2021"], 
		["PENIS PENIS PENIS, VAGINA VAGINA COCK COCK COCK! - KilobyteKeith Stardew Valley 01/25/2021"], 
		["you can only see so much warzone 5 days a week - tylersoyer Stardew Valley 01/25/2021"], 
		["let me get the peen into the vageeen and get to poundin’ - KilobyteKeith Stardew Valley 01/25/2021"], 
		["can you guys just entertain yourself so I can play video game’s?! - KilobyteKeith Stardew Valley 01/25/2021"], 
		["you’d have to go in head first, dick up - KilobyteKeith Stardew Valley 01/25/2021"], 
		["I was getting if gang banged - KilobyteKeith Call of Duty: Warzone 01/29/2021"], 
		["we like our girls to look like they just got pounded - KilobyteKeith Apex Legends 02/02/2021"], 
		["AHHH!! Fuck me!! And I’m not alone!! -ldNutz Apex Legends 02/02/2021"], 
		["do you really need throat pray to take a 9 pluser?! - KilobyteKeith Apex Legends 02/02/2021"], 
		["do you really need a throat spray to take a 9 pluser?! - KilobyteKeith Apex Legends 02/02/2021"], 
		["I'm going in fast and deep - KilobyteKeith Apex Legends 02/02/2021"], 
		["Did you guys know that if you're born feet first, there was a small amount of time you wore your mom as a hat -- KilobyteKeith Apex Legends 02/02/2021"], 
		["Strat would never play it, he’s a little bitch - KilobyteKeith Stardew Valley 02/03/2021"], 
		["can I milk the babies? Stardew Valley 02/03/2021"], 
		["always waiting for nuts to cum Stardew Valley 02/03/2021"], 
		["I would sleep with a cow KilobyteKeith Stardew Valley 02/03/2021"], 
		["Get off my little thing - KBK Call of Duty: Black Ops Cold War 02/04/2021"], 
		["omg brit I don't wanna feel your peen - KilobyteKeith Call of Duty: Black Ops Cold War 02/04/2021"], 
		["Make it rain on my pussy! -KilobyteKeith Call of Duty: Warzone 02/05/2021"], 
		["They only kiss me when they hit rock bottom - KilobyteKeith Hades 02/10/2021"], 
		["Binary he needs a big sloppy blowjob' - phantom_xander Hades 02/10/2021"], 
		["Try hitting your shot next time! - KilobyteKeith Call of Duty: Warzone 02/23/2021"], 
		["I'm scared but also kind of horny - rawr - KilobyteKeith Wick 03/04/2021"], 
		["I just rage farted - KilobyteKeith getting over it 03/04/2021"], 
		["it’s for the girls with stank puss - KilobyteKeith Murder House 03/11/2021"], 
		["wow if keke had 2 penises he would have one whole inch then lol - DesertSandBox The Complex 03/14/2021"], 
		["How many nights are there? - KilobyteKeith Five Nights at Freddy's 03/14/2021"], 
		["just throw me butt first - BinaryDigit Call of Duty: Warzone 03/19/2021"], 
		["Just finish all over my face - KilobyteKeith Call of Duty: Warzone 03/20/2021"], 
		["wow she could handle a 10 footer - BinaryDigit Little Nightmares II 03/24/2021"], 
		["are you talking about your butthole?! - KilobyteKeith Little Nightmares II 03/24/2021"], 
		["I will slap your mom and have sex with your dad - KilobyteKeith Fall Guys: Ultimate Knockout 04/04/2021"], 
		["I beat her for fun - Chesney Animal Crossing: New Horizons 04/08/2021"], 
		["I touched the titty and then bad things happened - KilobyteKeith IMSCARED 04/15/2021"], 
		["This is not how you bush - Danixghozt Call of Duty: Warzone 04/17/2021"], 
		["Fight me ho - Keith Call of Duty: Warzone 04/17/2021"], 
		["Accept my Ore you whore - Keith Stardew Valley 04/18/2021"], 
		["I have fully developed man hands - KilobyteKeith Apex Legends 04/23/2021"], 
		["What's that, a tiddie? -Keith P.T. 04/29/2021"], 
		["eat my ass anytime no dinner necessary - ldnutz P.T. 04/29/2021"], 
		["moans for kids!! - KilobyteKeith Call of Duty: Black Ops Cold War 04/30/2021"], 
		["shit in my MOUTH! - ldnutz Call of Duty: Black Ops Cold War 04/30/2021"], 
		["I just don't pee on my hands - KilobyteKeith New Pokémon Snap 05/02/2021"], 
		["Eat it bitch -- Keith New Pokémon Snap 05/02/2021"], 
		["I’m a gentle lover - KilobyteKeith New Pokémon Snap 05/02/2021"], 
		["Something always happens when you get it in the hole -bsquidwrd New Pokémon Snap 05/02/2021"], 
		["let's finish this guy off -KIlobyteKeith Dread X Collection: The Hunt 05/05/2021"], 
		["Put it in me - KilobyteKeith Dread X Collection: The Hunt 05/05/2021"], 
		["show, me, tits! - KilobyteKeith Nun Massacre 05/06/2021"], 
		["I wake up, I'm better than you, and when I go to sleep I'm better than you Call of Duty: Warzone 05/07/2021"], 
		["I wake up - I'm better than you - and when I go to sleep - I'm better than you -Kiloby Call of Duty: Warzone 05/07/2021"], 
		["You’re the type of person in the SAW movies that instantly let’s the other person die for money. - ChesneyO Resident Evil Village 05/09/2021"], 
		["Eat my ass. I don't care. I'll bend over. KilobyteKeith Resident Evil Village 05/10/2021"], 
		["I would agree with everything Brit said - iamzef666 and then repeated by Keke Resident Evil Village 05/10/2021"], 
		["Fucking stanky crotch. KilobyteKeith Resident Evil Village 05/10/2021"], 
		["I hate it, I never want to have sex again. KilobyteKeith Resident Evil Village 05/10/2021"], 
		["I just like going raw. Keke Resident Evil Village 05/11/2021"], 
		["Having sex with me is like McDonald's: Have it your way! Keke Resident Evil Village 05/11/2021"], 
		["Sex with me is like Burger King: When you're finished you get a paper hat. Keke Resident Evil Village 05/11/2021"], 
		["Sex with me is more like taco bell, not really ur first choice but after drinking that much who f'in cares -Kallyboo Resident Evil Village 05/11/2021"], 
		["If you want good dick posture, you should take off your underwear - Keke Resident Evil Village 05/11/2021"], 
		["Can you melk a pig? - Keke Resident Evil Village 05/11/2021"], 
		["You need a big fat hog in your house. Either adopt one or adopt me - Keke Resident Evil Village 05/11/2021"], 
		["I'm just unloading all over his face - Keke Resident Evil Village 05/11/2021"], 
		["Can't be selling the melk for free when I'm a cow - Keke Resident Evil Village 05/12/2021"], 
		["I'm cockless right now - Keke Resident Evil Village 05/12/2021"], 
		["I'm just gonna unload on his chest -KilobyteKeith Resident Evil Village 05/12/2021"], 
		["Nothing I hate more than a childs laughter -- Keith Resident Evil Village 05/12/2021"], 
		["If I was blue cheese I would eat myself. Time to start eating me - Keith Resident Evil Village 05/12/2021"], 
		["I am NOT okie dokie artichokie - Keke Resident Evil Village 05/12/2021"], 
		["I totally emptied my thing into you! - Binary Call of Duty: Warzone 05/14/2021"], 
		["dick - ChesneyO Call of Duty: Warzone 05/15/2021"], 
		["Suck the poop right outta my ass! - Keke Call of Duty: Warzone 05/16/2021"], 
		["Milkduds, good to suck on, just like titties - BinaryDigit Dead by Daylight 05/16/2021"], 
		["That’s what he calls my vagina actually Kreygasm -- Brit Hitchhiker 05/18/2021"], 
		["So that’s what happens when you drink pineapple juice - Chesney Hitchhiker 05/18/2021"], 
		["Come on Naldos sperm. Show me the way -- Keith Hitchhiker 05/18/2021"], 
		["this is the only way keke would see the inside of a vagina - BinaryDigit Hitchhiker 05/18/2021"], 
		["milf...don't need a tip, just a strap - KilobyteKeith Duck Season 05/19/2021"], 
		["I gotta come back, come face, come toes... - Keke Call of Duty: Warzone 05/22/2021"], 
		["I'm gonna kiss you right on the mouth - KilobyteKeith Call of Duty: Warzone 05/22/2021"], 
		["Naldo send me Del Taco, I'll cup your balls and lick them - KilobyteKeith Call of Duty: Warzone 05/22/2021"], 
		["the cool level around here is Binary, Chesney, everyone else in chat, me, whale poop, then keke - kallyboo Call of Duty: Warzone 05/22/2021"], 
		["out of guys in VC for sexyness ratings it'd be 1) Daniiiiii  kiloby1Gasm  2)Nutz and then people in chat oh wait no room for Keke - lillykitty0513 Call of Duty: Warzone 05/22/2021"], 
		["I'm like, at half chub right now - KilobyteKeith Call of Duty: Warzone 05/22/2021"], 
		["nobody knows who you are Chesney - KilobyteKeith Call of Duty: Warzone 05/22/2021"], 
		["I'm gonna black out - KilobyteKeith Call of Duty: Warzone 05/22/2021"], 
		["I'm 110lbs - KiloebyteKeith Call of Duty: Warzone 05/22/2021"], 
		["you ever take a shit and lose 5lbs? - KilobteKeith Call of Duty: Warzone 05/22/2021"], 
		["do you even KNOW all the 26 letters of the alphabet?..or was it 27? - KilobyteKeith Call of Duty: Warzone 05/22/2021"], 
		["I'm gonna fuck your dad and milk the cum outta him - Keke Call of Duty: Warzone 05/22/2021"], 
		["I'm not gay but you're tempting me right now - LDNutz Call of Duty: Warzone 05/22/2021"], 
		["Oh do I have tits? Nice. - Keke Subnautica: Below Zero 05/24/2021"], 
		["Ugh he's got his goo all over me - Keith Subnautica: Below Zero 05/24/2021"], 
		["That's giving me big cock ring energy right there - Keke Subnautica: Below Zero 05/24/2021"], 
		["I’m always thinking about mommies - KilobyteKeith Subnautica: Below Zero 05/24/2021"], 
		["Come lick my shrub nuts. - Keith Subnautica: Below Zero 05/24/2021"], 
		["I'm positive ion never gonna use one of those scam lamps - GO_Stratman: Erica 05/25/2021"], 
		["I have balls on my hair -- keith Erica 05/25/2021"], 
		["What were your favorite things? I like the touching -- Keith Erica 05/25/2021"], 
		["They call me Pizza Hut, I come in 30 minutes or it's free - Keith Convenience Store 05/27/2021"], 
		["It's just so wet -- Keith Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["right where i belong... on your face -- Binary Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["im scared for you well being keith - cannonthafan Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["spit that out! that's for Brit! - KilobyteKeith Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["boil the stank out - Naldo Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["you're not real friends unless you talk about drinking each others pee - KilobyteKeith Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["Never fits at first. You gotta work it- Naldo Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["NO I DID NOT FART - KiloebyteKeith\ Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["my thighs so nice they follow me twice - KilobyteKeith Pools, Hot Tubs, and Beaches 05/30/2021"], 
		["I'm not trying to touch you. I'm trying to get your mayonnaise -- Keith Stardew Valley 05/31/2021"], 
		["do not diss the sausage @DanixGhozt Stardew Valley 05/31/2021"], 
		["Maybe I'm too deep -- Keith Stardew Valley 05/31/2021"], 
		["Mom's got a WAP. That's what those goopy sounds are -- Keith Among the Sleep 06/03/2021"], 
		["I can just drink water or suck dicks constantly -- Binary Apex Legends 06/04/2021"], 
		["Keke good at juggling dudes -Garth Apex Legends 06/04/2021"], 
		["We'll guard your box Dani -- Keith Apex Legends 06/04/2021"], 
		["I mean...can I milk him? - Dani Among Us 06/06/2021"], 
		["yOuNgEr pEoPlE ArEn’t tYpIcAlLy wItTy, ThEy jUsT RePeAt tHe oFfIcE AnD SoMe dUmB StUfF - KilobyteKeith Stardew Valley 06/07/2021"], 
		["we gotta get Strat laid, if I gotta do it... I will bring the lube - KilobyteKeith Stardew Valley 06/07/2021"], 
		["I like my eggs with sperm please. Fully fertilized -- Keith Stardew Valley 06/07/2021"], 
		["I don’t care who sees my penis - KilobyteKeith Stardew Valley 06/07/2021"], 
		["I want people to see my penis and feel bad for me - KilobyteKeith Stardew Valley 06/07/2021"], 
		["OMNOMNOMNOMNOM! GIVE ME YOUR BABIES -- KilobyteKeith Stardew Valley 06/07/2021"], 
		["The only muscle I have is in my back from carrying you in Warzone - Keith Stardew Valley 06/07/2021"], 
		["It's a perfect fit -- Keith Stardew Valley 06/07/2021"], 
		["I will slobber on the Cobb all day. you know what I m mean Brows  -- Keith Stardew Valley 06/07/2021"], 
		["AHH fuck me in the ass, c'mon! - Keke Night Delivery 06/10/2021"], 
		["You know what they say. Bendy in the head, Freak in the bed -- Keith Night Delivery 06/10/2021"], 
		["We're going to hell. We're going straight down to hell -- Keith Night Delivery 06/10/2021"], 
		["This package is tiny! - Keith Night Delivery 06/10/2021"], 
		["OMG fuck yo' couch let's go! - 5spad3d Call of Duty: Warzone 06/12/2021"], 
		["it's a fuck fest Call of Duty: Warzone 06/12/2021"], 
		["Naldo is a bitch and I want everyone to know it - Keith Call of Duty: Warzone 06/12/2021"], 
		["Oh god, my ass is on fire! - Keith Call of Duty: Warzone 06/12/2021"], 
		["Back door is open - Keith Call of Duty: Warzone 06/12/2021"], 
		["if fat was getting rid of the heat you should never experience heat - Nutz The Evil Within 2 06/13/2021"], 
		["he runs like he had diarrhea - KilobyteKeith The Evil Within 2 06/13/2021"], 
		["Where's Vienna? Italy? hot Vienna sausages - Keke Stardew Valley 06/22/2021"], 
		["My artist gives me big enough size -- Keith Stardew Valley 06/22/2021"], 
		["That's alright, squirt all over me - Keith Stardew Valley 06/22/2021"], 
		["Oh god, i'm slimed... It's all over my face! - Keith Stardew Valley 06/22/2021"], 
		["It's so hard! it's supposed to be a gummy bear now a fucking rock Stardew Valley 06/28/2021"], 
		["Can I ram into him with the mushroom? -KilobyteKeith Mario Kart 8 07/03/2021"], 
		["I was 360'ing killers when you were still in your dad's ballsack - Keith Dead by Daylight 07/04/2021"], 
		["Also how do you quote? I keep forgetting to ask -CDawg Call of Duty: Warzone 07/09/2021"], 
		[" if anything you push your MOTHER to the edge because she didn't want you in her womb anymore .... - KitCait16 Call of Duty: Warzone 07/09/2021"], 
		["Ain't no fun if the homies can't have none - Keke Call of Duty: Warzone 07/10/2021"], 
		["I'm going hard butt right off the bat Jackbox Party Packs 07/11/2021"], 
		["Touch my crack - nutz Dead by Daylight 07/16/2021"], 
		["I love duos because I can take two guys at once - Keke Call of Duty: Warzone 07/24/2021"], 
		["Nippies -Keke Call of Duty: Warzone 07/24/2021"], 
		["He blue himself -- Keith Stardew Valley 07/25/2021"], 
		["No need to unload all over my face -- Keith Jupiter Hell 07/26/2021"], 
		["Come into my hallway -- Keith Jupiter Hell 07/26/2021"], 
		["we need Naldo - Nutz - during the great Keke Outage of 2021 Jupiter Hell 07/27/2021"], 
		["Imagine I go all the way with Chesney -- Keith Jupiter Hell 07/27/2021"], 
		["I just got blasted on my back -- Keith Call of Duty: Warzone 07/31/2021"], 
		["You want me to do the Keke? -- Nutz Call of Duty: Warzone 07/31/2021"], 
		["I always cum last - KilobyteKeith Fall Guys: Ultimate Knockout 08/01/2021"], 
		["Baked chips, basically a health food - Keke Sea of Thieves 08/02/2021"], 
		["well if it isn’t my old arch nemesis, Brit. I have yet to win a battle against her. She is TOO strong, beautiful and bodacious - KilobyteKeith LEGO Builder's Journey 08/10/2021"], 
		["Oh shit she nakie-I saw bush AND tittie! - Keke Visage 08/12/2021"], 
		["what's adequate for your hallway vags? - Apostle Visage 08/12/2021"], 
		["best film ever made. bust a nut in grandma's butt vol. 2 - Apostle Visage 08/12/2021"], 
		["Might as well look cute and show you my taco as I'm dying -- Binary Call of Duty: Warzone 08/13/2021"], 
		["Hey Keke did you know the moon only shows up in Vegas once every 6 months? -- Binary Visage 08/19/2021"], 
		["oh is it a full moon every where or just in vegas? - KiloDummyKeith Visage 08/19/2021"], 
		["You little bitch! Hope you step on a LEGO - Keith Call of Duty: Warzone 08/20/2021"], 
		["I was a good boy and haven't uploaded any cocks yet -- Keith Call of Duty: Warzone 08/27/2021"], 
		["Okay, you can take me now -- Nutz Call of Duty: Warzone 08/27/2021"], 
		["You make me dead hard -- Keith Call of Duty: Warzone 08/28/2021"], 
		["Like I said, I'm still tweaking 7 Days to Die 09/02/2021"], 
		["Smii's mouth about to be a daycare - Keke Call of Duty: Warzone 09/04/2021"], 
		["My hands were there, and they didn't come -- Keith Fall Guys: Ultimate Knockout 09/12/2021"], 
		["I feel like poon is gender neutral -- Keith Fall Guys: Ultimate Knockout 09/12/2021"], 
		["You fell right through the little hole -- Binary Fall Guys: Ultimate Knockout 09/12/2021"], 
		["Right through the pink head first -- Keith Fall Guys: Ultimate Knockout 09/12/2021"], 
		["I'll fly over there and make you eat the bean -- Keith Fall Guys: Ultimate Knockout 09/12/2021"], 
		["I'm not chewing it, I'm just sucking it in my mouth. Dead by Daylight 02/20/2020"], 
		["Just because you mate doesn't mean you are happy. Planet Zoo 03/15/2020"], 
		["Take it all over the chest. Control 05/27/2020"], 
		["I'm going in deep - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["OOH she's got a little pussy zipper! - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["I would like 1 wet dream please - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["How do I get my dick hard? - KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["can I take my pants off? - kilobytekeith Cyberpunk 2077 12/11/2020"], 
		["Lets put this dick to use, dick tease - kilobytekeith Cyberpunk 2077 12/11/2020"], 
		["i'll bring extra panties to cream in - BinaryDigit Cyberpunk 2077 12/11/2020"], 
		["I like when things get sticky -KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["I just want to see my dude's dick again! -KilobyteKeith Cyberpunk 2077 12/11/2020"], 
		["I like a deep slot - KilobyteKeith Amnesia: Rebirth 12/28/2020"], 
		["When in doubt, crank it out! - KilobyteKeith Amnesia: Rebirth 12/28/2020"], 
		["Where is the hole? I can't find it - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["Come on Dani, someone’s gotta show these hoes how to do it - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["make my pussy throb - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["I'll put anything in my mouth - KilobyteKeith Amnesia: Rebirth 12/29/2020"], 
		["I’ll ride the Keke Express - BinaryDigit Call of Duty: Warzone 12/31/2020"], 
		["Can I draw a penis on it? - KilobyteKeith Call of Duty: Warzone 12/31/2020"], 
		["I can't swallow -KiloybyteKeith Call of Duty: Warzone 12/31/2020"], 
		["I feel like I'm close - KilobyteKeith Song of Horror 01/03/2021"], 
		["Followin the ol’ jizz trail - KilobyteKeith Song of Horror 01/05/2021"], 
		["oh god!! It’s covered in jizz! Looks like my closet - KilobyteKeith Song of Horror 01/05/2021"], 
		["I hope every guy watching this is fully erect by the sound of my voice - KilobyteKeith Song of Horror 01/05/2021"], 
		["....just like stroking a dick - BinaryDigit Song of Horror 01/05/2021"], 
		["that right there is a vagina opener - KilobyteKeith Song of Horror 01/12/2021"], 
		["two in the pink, one in the stink - KilobyteKeith Song of Horror 01/12/2021"], 
		["How do I start blowing? -- KilobyteBot Song of Horror 01/12/2021"], 
		["you better bring some bitches Tyler cuz we’re gonna fuck em RAW - KilobyteKeith Song of Horror 01/12/2021"], 
		["You remind me of my pinkie toe...little, cute and I'll probably bang you on the coffee table later tonight. - Tylersoyer Song of Horror 01/12/2021"], 
		["Get your bitch ass pussy out my face - KilobyteKeith Song of Horror 01/12/2021"], 
		["Britt would be wild and probably put five fingers in ya Binary. Use you like a sock puppet -- KilobyteKeith Song of Horror 01/12/2021"], 
		["nothing wrong with walking in a room and getting fucked - Tylersoyer Song of Horror 01/12/2021"], 
		["AHHH FUCK ME IN THE ASS!! - KilobyteKeith Song of Horror 01/13/2021"], 
		["My hands are NOT on my cock! - KilobyteKeith The House of the Dead: Overkill 01/14/2021"], 
		["portable hand jobs now - Tylersoyer The House of the Dead: Overkill 01/14/2021"], 
		["No I will stay wet - BinaryDigit Call of Duty: Black Ops Cold War 01/17/2021"], 
		["She's also aware of my big black cock fetish - KilobyteKeith Call of Duty: Black Ops Cold War 01/17/2021"], 
		["Hey at least when we order a Keke version of a penis we end up getting a loose vagina instead #WishFails - RoyalBrrittneyyygns Stardew Valley 01/24/2021"], 
		["even if you have A cups, I don’t care, I’ll still suck them - KilobyteKeith Stardew Valley 01/24/2021"], 
		["PENIS PENIS PENIS, VAGINA VAGINA COCK COCK COCK! - KilobyteKeith Stardew Valley 01/25/2021"], 
		["you can only see so much warzone 5 days a week - tylersoyer Stardew Valley 01/25/2021"], 
		["let me get the peen into the vageeen and get to poundin’ - KilobyteKeith Stardew Valley 01/25/2021"], 
		["can you guys just entertain yourself so I can play video game’s?! - KilobyteKeith Stardew Valley 01/25/2021"], 
		["you’d have to go in head first, dick up - KilobyteKeith Stardew Valley 01/25/2021"], 
		["I was getting if gang banged - KilobyteKeith Call of Duty: Warzone 01/29/2021"], 
		["we like our girls to look like they just got pounded - KilobyteKeith Apex Legends 02/02/2021"], 
		["AHHH!! Fuck me!! And I’m not alone!! -ldNutz Apex Legends 02/02/2021"], 
		["do you really need throat pray to take a 9 pluser?! - KilobyteKeith Apex Legends 02/02/2021"], 
		["do you really need a throat spray to take a 9 pluser?! - KilobyteKeith Apex Legends 02/02/2021"], 
		["I'm going in fast and deep - KilobyteKeith Apex Legends 02/02/2021"], 
		["Did you guys know that if you're born feet first, there was a small amount of time you wore your mom as a hat -- KilobyteKeith Apex Legends 02/02/2021"], 
		["Strat would never play it, he’s a little bitch - KilobyteKeith Stardew Valley 02/03/2021"], 
		["can I milk the babies? Stardew Valley 02/03/2021"], 
		["always waiting for nuts to cum Stardew Valley 02/03/2021"], 
		["I would sleep with a cow KilobyteKeith Stardew Valley 02/03/2021"], 
		["Get off my little thing - KBK Call of Duty: Black Ops Cold War 02/04/2021"], 
		["omg brit, I don't wanna feel your peen - KilobyteKeith Call of Duty: Black Ops Cold War 02/04/2021"], 
		["Make it rain on my pussy! -KilobyteKeith Call of Duty: Warzone 02/05/2021"], 
		["They only kiss me when they hit rock bottom - KilobyteKeith Hades 02/10/2021"], 
		["Binary he needs a big sloppy blowjob' - phantom_xander Hades 02/10/2021"], 
		["Try hitting your shot next time! - KilobyteKeith Call of Duty: Warzone 02/23/2021"], 
		["I'm scared but also kind of horny - rawr - KilobyteKeith Wick 03/04/2021"], 
		["I just rage farted - KilobyteKeith getting over it 03/04/2021"], 
		["it’s for the girls with stank puss - KilobyteKeith Murder House 03/11/2021"], 
		["wow if keke had 2 penises he would have one whole inch then lol - DesertSandBox The Complex 03/14/2021"], 
		["How many nights are there? - KilobyteKeith Five Nights at Freddy's 03/14/2021"], 
		["just throw me butt first - BinaryDigit Call of Duty: Warzone 03/19/2021"], 
		["Just finish all over my face - KilobyteKeith Call of Duty: Warzone 03/20/2021"], 
		["wow she could handle a 10 footer - BinaryDigit Little Nightmares II 03/24/2021"], 
		["are you talking about your butthole?! - KilobyteKeith Little Nightmares II 03/24/2021"], 
		["I will slap your mom and have sex with your dad - KilobyteKeith Fall Guys: Ultimate Knockout 04/04/2021"], 
		["I beat her for fun - Chesney Animal Crossing: New Horizons 04/08/2021"], 
		["I touched the titty and then bad things happened - KilobyteKeith IMSCARED 04/15/2021"], 
		["This is not how you bush - Danixghozt Call of Duty: Warzone 04/17/2021"], 
		["Fight me ho - Keith Call of Duty: Warzone 04/17/2021"], 
		["Accept my Ore you whore - Keith Stardew Valley 04/18/2021"], 
		["I’ve never been able to give it to another player before! -keke Stardew Valley 11/14/2021"], 
		["I've gotta eat before I come -- Keith Minecraft 11/18/2021"], 
		["Watch my hole have everything -- Chesney Minecraft 11/18/2021"], 
		["I just squirted all over the mic -- Keke Dead by Daylight 11/24/2021"], 
		["Fuck me and suck me - Keke Dead by Daylight 11/24/2021"], 
		["I hope these are not hard to get off is the title of your sex tape - Strat Dead by Daylight 11/25/2021"], 
		["about a FUPA You gotta lift that shit up like you're changing oil - Keke Dead by Daylight 11/25/2021"], 
		["One of them's got TTV, I bet he's gonna lose -Keke Fall Guys: Ultimate Knockout 11/25/2021"], 
		["Fall Guys dildos I bet those would feel real good going up your butt -Keke Fall Guys: Ultimate Knockout 11/26/2021"], 
		["Fsinuviniunibiybds nsdpi nfsndfli mfd do d - Chesney Fall Guys: Ultimate Knockout 11/26/2021"], 
		["Didn't Jesus have a tattoo? - Keke Call of Duty: Warzone 11/27/2021"], 
		["69% more kills with KeKe Ultra Gamer Lube - Naldo Stardew Valley 11/28/2021"], 
		["Sorry I rode you so hard girlhorse... here's some food - Keke Red Dead Redemption 2 12/07/2021"], 
		["It's always been my dream to be hog tied - Keke Red Dead Redemption 2 12/07/2021"], 
		["Dani, I was juggling 3 guys at once alright - Keke Call of Duty: Warzone 12/10/2021"], 
		["I could have jerked off 2 times by the time this game loads in - Keke Call of Duty: Warzone 12/11/2021"], 
		["You subbed to them on your alt account - Go_Fapman Halo Infinite 12/18/2021"], 
		["leave some room for Jesus, guys - KilobyteKeith Stardew Valley 01/30/2022"], 
		["Just how nutz came prematurely, I have also arrived - Keith WWE 2K20 02/03/2022"], 
		["KEKE A JEALOUS BITCH - Chesney WWE 2K20 02/04/2022"], 
		["Eat my Mayo Bitch -keke Stardew Valley 02/17/2022"], 
		["Nice hole, I’ve seen bigger. Last night I had a real nice one -keke Stardew Valley 02/21/2022"], 
		["I'm very familiar with 5 cm - Samwise The Forest 02/25/2022"], 
		["if she ain't pooping she smoking (referring to Chesney) -kitcait16 Stardew Valley 02/27/2022"], 
		["Apparently you have to unhoe to lay your seed - Keke Stardew Valley 02/28/2022"], 
		["They are all sticky and in my hands and I don't like it - Keke Stardew Valley 02/28/2022"], 
		["Naldo could pull anything off of ME, to be honest - KilobyteKeith Stardew Valley 03/06/2022"], 
		["I just gave him some flappy bits - Keke WWE 2K22 03/12/2022"], 
		["That's why I've never been in a threesome. Just never liked the number 3 -- Keith Core Keeper 03/14/2022"], 
		["Lips are lips. They all feel the same in the end -- Keith Core Keeper 03/14/2022"], 
		["Man this is taking forever, am I hittin it right? -keke Core Keeper 03/14/2022"], 
		[" i remember more than you ever will - Chesney Core Keeper 03/14/2022"], 
		["It's like putting on your favorite crocheted penis cover - Keke Call of Duty: Warzone 03/18/2022"]
		];


var currentQuote = "";
var currentAuthor = "";
var randomquote = "";

function getQuote() {
	randomquote = Math.floor(Math.random() * quotes.length);
    currentQuote = quotes[randomquote][0];
    currentAuthor = quotes[randomquote][1];

	$(document).ready(function () {
	    $('#quotetext').text(currentQuote);
		$('#newquote').on('click', getQuote);
	});
    
}

getQuote();